version: '3'
services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=authdb
      - DB_USERNAME=admin
      - DB_PASSWORD=adminpassword
      - JWT_SECRET=mysecretkey

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3001:3000"
    depends_on:
      - mongodb

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3002:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
